repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--config=black.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
