semantic_segmentation_model:
  pretrained: False
data:
  dataloader:
    batch_size: 16
    num_workers: 0
  preprocessing:
    - Resize:
        height: 128
        width: 128
device: cpu
hydra:
  run:
    dir: ${config_dir:}/outputs
optim:
  epochs: 1
policy_model:
  num_sub_policies: 10
seed: 42
